spring:
  application:
    name: test-rabbitmq  #应用名，配不配都可以
  rabbitmq:
    host: 192.168.6.196  #配置mq主机地址
    port: 5672           #端口
    virtual-host: /ems   #虚拟主机
    username: ems        #绑定该虚拟主机的用户名
    password: 123        #绑定该虚拟主机的密码
    publisher-confirm-type: simple  #开启消息确认模式
    publisher-returns: true  #使用return机制
